In [11]:
import pandas as pd
import numpy as np

In [45]:
data = pd.read_csv(r'C:\Users\Admin\Desktop\DPL+EDA+PDS\Final_ObesityDataset (1).csv')

In [3]:
data.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21,1.62,64.0,yes,no,2,3,Sometimes,no,2.0,no,0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56.0,yes,no,3,3,Sometimes,yes,3.0,yes,3,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.80,77.0,yes,no,2,3,Sometimes,no,2.0,no,2,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.80,87.0,no,no,3,3,Sometimes,no,2.0,no,2,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.8,no,no,2,1,Sometimes,no,2.0,no,0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
data.dtypes

Gender                             object
Age                                 int64
Height                            float64
Weight                            float64
family_history_with_overweight     object
FAVC                               object
FCVC                                int64
NCP                                 int64
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                                 int64
TUE                               float64
CALC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

In [6]:
data.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [7]:
data['BMI'] = data['Weight'] / (data['Height'] ** 2)

In [22]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [23]:
data['Gender'].value_counts()

Gender
Male      1068
Female    1043
Name: count, dtype: int64

In [26]:
data['family_history_with_overweight'].unique()

array(['yes', 'no'], dtype=object)

In [27]:
data['family_history_with_overweight'].value_counts()

family_history_with_overweight
yes    1726
no      385
Name: count, dtype: int64

In [28]:
data['FAVC'].unique()

array(['no', 'yes'], dtype=object)

In [29]:
data['FAVC'].value_counts()

FAVC
yes    1866
no      245
Name: count, dtype: int64

In [30]:
data['CAEC'].unique()

array(['Sometimes', 'Frequently', 'Always', 'no'], dtype=object)

In [31]:
data['CAEC'].value_counts()

CAEC
Sometimes     1765
Frequently     242
Always          53
no              51
Name: count, dtype: int64

In [33]:
#data['SMOKE'].unique()
data['SMOKE'].value_counts()

SMOKE
no     2067
yes      44
Name: count, dtype: int64

In [34]:
data['CALC'].value_counts()

CALC
Sometimes     1401
no             639
Frequently      70
Always           1
Name: count, dtype: int64

In [35]:
data['MTRANS'].value_counts()

MTRANS
Public_Transportation    1580
Automobile                457
Walking                    56
Motorbike                  11
Bike                        7
Name: count, dtype: int64

In [37]:
data['NObeyesdad'].value_counts()

NObeyesdad
Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: count, dtype: int64

In [9]:
bins = [0, 18, 35, 60, 100]
labels = ['Teen', 'Young_Adult', 'Adult', 'Senior']
data['Age_Group'] = pd.cut(data['Age'], bins=bins, labels=labels, right=False)

In [13]:
conditions = [
    (data['FAVC'] == 'yes') & (data['NCP'] == 3) & (data['CAEC'] == 'Frequently'),
    (data['FAVC'] == 'yes') & (data['CAEC'] == 'Frequently'),
    (data['FAVC'] == 'yes') & (data['NCP'] == 3)
]
choices = ['High', 'High', 'High']
data['High_Caloric_Intake'] = np.select(conditions, choices, default='Low')

In [14]:
conditions = [
    (data['SCC'] == 'yes') & (data['FCVC'] >= 2) & (data['FAF'] >= 2),
    (data['SCC'] == 'yes') & (data['FAF'] >= 2),
    (data['SCC'] == 'yes') & (data['FCVC'] >= 2)
]
choices = ['High', 'High', 'High']
data['Health_Conscious'] = np.select(conditions, choices, default='Low')

In [17]:
data['Active_Lifestyle'] = data['MTRANS'].apply(lambda x: 'Active' if x in ['Walking', 'Bike'] else 'Sedentary')

In [16]:
data['Sedentary_Score'] = 3 - data['FAF'] + data['TUE']

In [38]:
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,...,TUE,CALC,MTRANS,NObeyesdad,BMI,Age_Group,High_Caloric_Intake,Health_Conscious,Active_Lifestyle,Sedentary_Score
0,Female,21,1.62,64.00,yes,no,2,3,Sometimes,no,...,1.0,no,Public_Transportation,Normal_Weight,24.386526,Young_Adult,Low,Low,Sedentary,4.0
1,Female,21,1.52,56.00,yes,no,3,3,Sometimes,yes,...,0.0,Sometimes,Public_Transportation,Normal_Weight,24.238227,Young_Adult,Low,High,Sedentary,0.0
2,Male,23,1.80,77.00,yes,no,2,3,Sometimes,no,...,1.0,Frequently,Public_Transportation,Normal_Weight,23.765432,Young_Adult,Low,Low,Sedentary,2.0
3,Male,27,1.80,87.00,no,no,3,3,Sometimes,no,...,0.0,Frequently,Walking,Overweight_Level_I,26.851852,Young_Adult,Low,Low,Active,1.0
4,Male,22,1.78,89.80,no,no,2,1,Sometimes,no,...,0.0,Sometimes,Public_Transportation,Overweight_Level_II,28.342381,Young_Adult,Low,Low,Sedentary,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20,1.71,131.41,yes,yes,3,3,Sometimes,no,...,0.9,Sometimes,Public_Transportation,Obesity_Type_III,44.940324,Young_Adult,High,Low,Sedentary,2.9
2107,Female,21,1.75,133.74,yes,yes,3,3,Sometimes,no,...,0.6,Sometimes,Public_Transportation,Obesity_Type_III,43.670204,Young_Adult,High,Low,Sedentary,2.6
2108,Female,22,1.75,133.69,yes,yes,3,3,Sometimes,no,...,0.6,Sometimes,Public_Transportation,Obesity_Type_III,43.653878,Young_Adult,High,Low,Sedentary,2.6
2109,Female,24,1.74,133.35,yes,yes,3,3,Sometimes,no,...,0.6,Sometimes,Public_Transportation,Obesity_Type_III,44.044788,Young_Adult,High,Low,Sedentary,2.6
2110,Female,23,1.74,133.47,yes,yes,3,3,Sometimes,no,...,0.7,Sometimes,Public_Transportation,Obesity_Type_III,44.084423,Young_Adult,High,Low,Sedentary,2.7

In [47]:
data['Gender'] = data['Gender'].map({'Male':0,'Female':1})

In [51]:
binary_mapping = {'yes': 1, 'no': 0}
binary_columns = ['family_history_with_overweight', 'FAVC', 'SMOKE', 'SCC']
for col in binary_columns:
    data[col] = data[col].map(binary_mapping)

In [52]:
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21,1.62,64.00,NaN,NaN,2,3,Sometimes,NaN,2.0,NaN,0,1.0,no,Public_Transportation,Normal_Weight
1,1,21,1.52,56.00,NaN,NaN,3,3,Sometimes,NaN,3.0,NaN,3,0.0,Sometimes,Public_Transportation,Normal_Weight
2,0,23,1.80,77.00,NaN,NaN,2,3,Sometimes,NaN,2.0,NaN,2,1.0,Frequently,Public_Transportation,Normal_Weight
3,0,27,1.80,87.00,NaN,NaN,3,3,Sometimes,NaN,2.0,NaN,2,0.0,Frequently,Walking,Overweight_Level_I
4,0,22,1.78,89.80,NaN,NaN,2,1,Sometimes,NaN,2.0,NaN,0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,1,20,1.71,131.41,NaN,NaN,3,3,Sometimes,NaN,1.7,NaN,1,0.9,Sometimes,Public_Transportation,Obesity_Type_III
2107,1,21,1.75,133.74,NaN,NaN,3,3,Sometimes,NaN,2.0,NaN,1,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2108,1,22,1.75,133.69,NaN,NaN,3,3,Sometimes,NaN,2.1,NaN,1,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2109,1,24,1.74,133.35,NaN,NaN,3,3,Sometimes,NaN,2.9,NaN,1,0.6,Sometimes,Public_Transportation,Obesity_Type_III
2110,1,23,1.74,133.47,NaN,NaN,3,3,Sometimes,NaN,2.9,NaN,1,0.7,Sometimes,Public_Transportation,Obesity_Type_III

In [ ]:
# Consolidated code to generate the new columns based on heuristic assumptions

def generate_columns(dataset):
    # 1. History_NObeyesdad
    dataset["History_NObeyesdad"] = dataset["family_history_with_overweight"] + "_" + dataset["NObeyesdad"]

    # 2. Obesity_Risk
    conditions_obesity_risk = [
        dataset['NObeyesdad'].str.contains('Obesity'),
        dataset['NObeyesdad'].str.contains('Overweight'),
        dataset['NObeyesdad'].str.contains('Normal_Weight')
    ]
    choices_obesity_risk = ['High', 'Moderate', 'Low']
    dataset['Obesity_Risk'] = np.select(conditions_obesity_risk, choices_obesity_risk, default='Low')

    # 3. Dietary_Habits
    conditions_dietary_habits = [
        (dataset['FAVC'] == 'yes') & (dataset['CH2O'] <= 2),
        (dataset['FAVC'] == 'no') & (dataset['CH2O'] > 2),
    ]
    choices_dietary_habits = ['Poor', 'Good']
    dataset['Dietary_Habits'] = np.select(conditions_dietary_habits, choices_dietary_habits, default='Average')

    # 4. Health_Monitoring
    conditions_health_monitoring = [
        (dataset['SCC'] == 'yes') & (dataset['FAF'] > 1),
        (dataset['SCC'] == 'no') & (dataset['FAF'] <= 1),
    ]
    choices_health_monitoring = ['Attentive', 'Negligent']
    dataset['Health_Monitoring'] = np.select(conditions_health_monitoring, choices_health_monitoring, default='Average')

    # 5. Lifestyle_Score
    conditions_lifestyle_score = [
        (dataset['FAF'] > 1) & (dataset['TUE'] > 1),
        (dataset['FAF'] <= 1) & (dataset['TUE'] <= 1),
    ]
    choices_lifestyle_score = ['Active', 'Sedentary']
    dataset['Lifestyle_Score'] = np.select(conditions_lifestyle_score, choices_lifestyle_score, default='Balanced')

    # 6. Risk_Factors
    conditions_risk_factors = [
        (dataset['family_history_with_overweight'] == 'yes') & (dataset['CALC'].isin(['Frequently', 'Always'])),
        (dataset['family_history_with_overweight'] == 'no') & (dataset['CALC'].isin(['no', 'Sometimes']))
    ]
    choices_risk_factors = ['High_Risk', 'Low_Risk']
    dataset['Risk_Factors'] = np.select(conditions_risk_factors, choices_risk_factors, default='Moderate_Risk')

    # 7. Daily_Routine
    conditions_daily_routine = [
        (dataset['NCP'] > 3) & (dataset['FAF'] > 1),
        (dataset['NCP'] <= 2) & (dataset['FAF'] <= 1)
    ]
    choices_daily_routine = ['Regular', 'Irregular']
    dataset['Daily_Routine'] = np.select(conditions_daily_routine, choices_daily_routine, default='Average')

    # 8. Transport_Physical_Activity
    conditions_transport_activity = [
        dataset['MTRANS'] == 'Walking',
        dataset['MTRANS'] == 'Bike'
    ]
    choices_transport_activity = ['Highly_Active', 'Moderately_Active']
    dataset['Transport_Physical_Activity'] = np.select(conditions_transport_activity, choices_transport_activity, default='Sedentary')

    # 9. Environmental_Factors
    conditions_environmental_factors = [
        dataset['NObeyesdad'].str.contains('Obesity'),
        dataset['NObeyesdad'].str.contains('Overweight')
    ]
    choices_environmental_factors = ['High_Risk', 'Moderate_Risk']
    dataset['Environmental_Factors'] = np.select(conditions_environmental_factors, choices_environmental_factors, default='Low_Risk')
    
    return dataset

# Apply the function to generate columns on the initial dataset
obesity_dataset_updated = generate_columns(obesity_dataset.copy())

# Display the first few rows with the new columns
obesity_dataset_updated.head()